#!/usr/bin/env python
import sys
import re

quote_or_backslash = re.compile(r'(["\\])')

(_name, var, path) = sys.argv

with open(path, 'rb') as fh:
    linum = 1
    for line in fh:
        if linum == 1:
            print var, "=", '"""',
        # add literal backslash before character
        print quote_or_backslash.sub(r'\\\1', line),
        linum += 1
    print '"""',
