#!/bin/bash
set -e

if [ -z $1 ]
then
    echo "Usage: ./reel reel_script.rl [options] [traildb.tdb]"
    exit 1
fi

#if [ -z $TRAILDB ]
#then
#    echo "Set TRAILDB to point at the root of the TrailDB repo"
#    exit 1
#fi

SOURCE=$1
shift

if [ $DEBUG ]
then
    WARN="-Wall -Wno-unused-label -Wno-unused-function"
else
    WARN="-Wno-format -Wno-incompatible-pointer-types"
fi

rm -f reel_query reel_script.c reel_script.h
./reel_compile $SOURCE
gcc $WARN\
    -o reel_query\
    -g\
    -O3\
    -L $TRAILDB/build\
    -I .\
    -I $TRAILDB/src/\
    reel_query.c reel_util.c reel_script.c thread_util.c\
    -ltraildb\
    -lJudy\
    -lpthread

if [ $# -ne 0 ]
then
    LD_LIBRARY_PATH=$TRAILDB/build ./reel_query $@
else
    echo "reel_query compiled successfully"
fi
